ihub-pub/plugins

.github/dependabot.yml

👷 调整版本自动升级策略

---

gradle.properties
ihub-plugins/build.gradle

👷 调整组件依赖配置版本

---

ihub-plugins/src/main/resources/META-INF/codenarc.groovy

🐛 修复CodeNarc编码问题

---

docs/_sidebar.md
docs/iHubSettings.md
ihub-plugins/build.gradle
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsExtension.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

📝 完善设置插件文档

---

docs/explanation.md
docs/iHubBoot.md
docs/iHubNative.md
docs/iHubTest.md

📝 完善spring插件文档

---

docs/iHub.md
docs/iHubSettings.md
docs/index.html
docs/js/version.js
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

✏️ 修正阿里云代理仓库不同步导致的构建失败问题

---

docs/iHubBom.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBomPluginTest.groovy

✏️ bom组件支持配置强制组件版本

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

✏️ 添加gradle版本检查

---

docs/iHubBom.md
docs/iHubJava.md
docs/iHubSettings.md
ihub-plugins/build.gradle
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

✨ ihub-java插件集成MapStruct依赖配置

---

docs/iHub.md
docs/iHubJava.md
docs/iHubSettings.md
ihub-aware/src/main/groovy/pub/ihub/plugin/IHubProjectProperty.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy

✏️ ihub-java插件配置整理

---

docs/iHubBom.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBomPluginTest.groovy

✏️ 按需使用io.spring.dependency-management插件

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy

⬆️ 升级ihub-bom至1.0.4

---

docs/iHubBoot.md
docs/iHubNative.md
docs/iHubPublish.md
docs/iHubSettings.md
docs/iHubVerification.md
gradle/wrapper/gradle-wrapper.properties
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/spring/IHubBootPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/spring/IHubNativeExtension.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

✨ ihub-settings支持自动配置项目bom组件

---

docs/iHubNative.md
ihub-plugins/build.gradle
ihub-plugins/src/main/groovy/pub/ihub/plugin/spring/IHubNativeExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/spring/IHubNativePlugin.groovy

⬆️ 升级spring-aot插件版本至0.11.1

---

docs/iHubBom.md
ihub-plugins/build.gradle
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy

🎨 默认bom组件改用ihub-libs

---

docs/iHubJava.md
ihub-plugins/build.gradle
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

✨ 集成JMoleculesPlugin

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

🐛 修正无配文件项目替换组件版本报错，新年快乐🎆

---

docs/explanation.md
docs/iHubBoot.md
docs/iHubTest.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubSystemProperties.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/spring/IHubBootExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/spring/IHubBootPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/verification/IHubTestExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy

🎨 Java运行时本地系统属性扩展优化

---

docs/iHub.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/githooks/IHubGitHooksPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

✏️ 主项目默认添加ihub-git-hooks插件

---

docs/iHubTest.md
docs/iHubVerification.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy

✨ 集成test-report-aggregation聚合测试报告

---

docs/iHubSettings.md
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

✏️ 移除阿里云Gradle插件代理仓库

---

gradle/wrapper/gradle-wrapper.properties

build(gradle): 升级gradle至7.4.2

---

ihub-plugins/build.gradle
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy

build(gradle): 升级plugin-publish、spring-aot组件版本

---

.github/workflows/gradle-build.yml
docs/iHub.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

feat(version): 支持通过最新的tag推断下一个版本号

---

.github/workflows/gradle-publish.yml
samples/sample-multi/rest/build.gradle

ci(github): 发布release前需要完整构建，避免再次发版翻车

---

ihub-plugins/build.gradle

build(gradle): 升级spring-aot组件版本 (#261)

---

docs/iHub.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

feat(repo): 支持阿里云代理仓库启用参数

---

docs/iHubBom.md
docs/iHubJava.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/impl/Capability.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/impl/CapabilitySpecImpl.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/specs/CapabilitySpec.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBomPluginTest.groovy
samples/sample-extensions/bom.gradle

feat(bom): 支持配置组件功能以及组件需要能力

---

.github/workflows/gradle-build.yml
.github/workflows/gradle-publish.yml

ci(github): 调整工作流组件版本

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy

fix(java): 修正组件多个能力配置失败的问题

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBomPluginTest.groovy
samples/sample-extensions/bom.gradle
samples/sample-groovy/settings.gradle
samples/sample-multi/settings.gradle

feat(java): 调整组件能力依赖方式

---

docs/iHubJava.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBomPluginTest.groovy

feat(encoding): ihub-java插件添加Java编译编码配置，默认UTF-8

---

docs/iHubVerification.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationExtension.groovy

feat(version): 升级PMD、Codenarc、Jacoco版本

---

ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy
samples/sample-groovy/gradle/wrapper/gradle-wrapper.properties
samples/sample-multi/gradle/wrapper/gradle-wrapper.properties
samples/sample-multi/settings.gradle

fix(test): 修正测试用例

---

gradle/wrapper/gradle-wrapper.properties

build(gradle): 升级gradle至7.5.1

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy

test(version): 修复版本号推断测试用例

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubVerificationPluginTest.groovy

fix(spock): 修复spock测试缺失spring测试组件依赖的问题

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy

feat: 启用阿里云代理仓库开关支持系统属性和环境变量属性配置

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubBasicPluginTest.groovy

feat(java): iHubJava的log依赖中添加jcl-over-slf4j

---

ihub-test/build.gradle

ci(gradle): 修正ihub-test模块配置

---

ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

test: 补充测试用例

---

.github/dependabot.yml
build.gradle
gradle.properties
ihub-bom/build.gradle
ihub-java/build.gradle
ihub-plugins/build.gradle
ihub-publish/build.gradle
ihub-spring/build.gradle

revert(bom): 还原公共平台组件配置

---

ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy

fix(bom): bom组件项目不使用ihub-bom插件

---

ihub-groovy/src/main/groovy/pub/ihub/plugin/groovy/IHubGroovyPlugin.groovy
ihub-groovy/src/test/groovy/pub/ihub/plugin/groovy/IHubGroovyPluginTest.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy

feat(groovy): 移除enableGroovy3扩展属性

---

ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

test(verification): 修正测试用例

---

ihub-plugins/src/main/resources/META-INF/codenarc.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
samples/sample-groovy/conf/codenarc/codenarc.groovy

fix(verification): 替换测试报告弃用方法

---

gradle/wrapper/gradle-wrapper.properties

build(github): 升级gradle至8.0.1

---

.github/workflows/gradle-build.yml
.github/workflows/gradle-publish.yml

ci(github): 工作流的Actions使用具体版本号

---

.github/workflows/gradle-build.yml
.github/workflows/gradle-publish.yml
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy

feat(repo): 默认禁用阿里云代理仓库

---

ihub-base-test/build.gradle
ihub-base/build.gradle
ihub-githooks/build.gradle
ihub-settings/build.gradle

build(publish): 修正插件tags配置

---

.github/workflows/gradle-build.yml
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-java/src/test/groovy/pub/ihub/plugin/java/IHubJavaPluginTest.groovy

使用配置如下：
```properties
iHubJava.complierArgs=-proc:none -nowarn
```
Closes: #392

feat(java): ihub-java插件添加编译扩展属性complierArgs

---

.github/workflows/gradle-build.yml
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy

feat(verification): 调整jacoco聚合报告任务依赖关系

---

gradle/wrapper/gradle-wrapper.properties

build(gradle): 升级gradle至8.0.2

---

ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-java/src/test/groovy/pub/ihub/plugin/java/IHubJavaPluginTest.groovy

build(gradle): 纠正typo：complierArgs -> compilerArgs

---

.github/workflows/gradle-build.yml
README.md
build.gradle
ihub-base-test/src/main/groovy/pub/ihub/plugin/test/IHubSpecification.groovy
ihub-base-test/src/test/groovy/pub/ihub/plugin/test/IHubSpecificationTest.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubPluginBaseTest.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-githooks/build.gradle
ihub-githooks/src/test/groovy/pub/ihub/plugin/githooks/IHubGitHooksPluginTest.groovy
ihub-groovy/src/test/groovy/pub/ihub/plugin/groovy/IHubGroovyPluginTest.groovy
ihub-java/src/test/groovy/pub/ihub/plugin/java/IHubJavaPluginTest.groovy
ihub-plugins/build.gradle
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/copyright/IHubCopyright.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/copyright/IHubCopyrightPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/version/IHubVersionExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/version/IHubVersionPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/copyright/IHubCopyrightPluginTest.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/version/IHubVersionPluginTest.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy
ihub-spring/src/test/groovy/pub/ihub/plugin/spring/IHubBootPluginTest.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationExtension.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

feat(copyright): 新增ihub-copyright插件

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/copyright/IHubCopyrightPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/copyright/IHubCopyrightPluginTest.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy

chore(verification): 根项目test、check任务不再依赖两个聚合任务

---

.github/workflows/gradle-publish.yml
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishExtension.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy

用以控制是否应用GithubPom插件，这个插件只有在发布组件时才需要使用

feat(publish): 添加扩展参数applyGithubPom

---

.github/workflows/doc.yml
.github/workflows/gradle-build.yml
.github/workflows/gradle-dependency-submission.yml
.github/workflows/gradle-publish.yml
docs/.vuepress/config.ts
docs/.vuepress/styles/index.scss
docs/.vuepress/theme.ts
docs/README.md
docs/advanced/multiAdvanced.md
docs/basics/gradleBasic.md
docs/basics/groovyBasic.md
docs/basics/singleBasic.md
docs/iHub.md
docs/iHubBom.md
docs/iHubBoot.md
docs/iHubCopyright.md
docs/iHubGitHooks.md
docs/iHubGroovy.md
docs/iHubJava.md
docs/iHubNative.md
docs/iHubPublish.md
docs/iHubSettings.md
docs/iHubTest.md
docs/iHubVerification.md
docs/iHubVersion.md
docs/snippet/explanation.md
docs/snippet/gradle-wrapper.properties.md
docs/snippet/setting.gradle.md
package-lock.json
package.json

docs: 文档整理

---

.github/dependabot.yml
.github/workflows/doc.yml
.github/workflows/gradle-build.yml
.github/workflows/gradle-dependency-submission.yml
.github/workflows/gradle-publish.yml

ci(github): 调整CI/CD流程

---

.github/workflows/gradle-build.yml
README.md
build.gradle

ci(github): 启用Gradle构建扫描

---

ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy
settings.gradle

fix(publish): 修正publish插件签名配置

---

ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishExtension.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy

feat(publish): ihub-publish插件添加publishSources扩展

---

.github/workflows/gradle-publish.yml
settings.gradle

ci(gradle): 组件发布时不发布源码

---

README.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-settings/build.gradle
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy
ihub-verification/src/main/resources/META-INF/codenarc.groovy
libs.versions.toml

feat(gradle): 移除SpringRelease仓库配置

---

README.md
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy

feat(repo): 移除仓库AliYunGoogle、AliYunSpring

---

ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsExtension.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

feat(settings): 移除扩展配置prefix默认值

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

feat: 添加是否启用私有仓库开关

---

build.gradle

build(deps): 升级com.github.ben-manes:gradle-versions-plugin版本

---

gradle.properties
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy
settings.gradle

feat(settings): 自动配置根目录.versions.toml文件

---

build.gradle.kts

build(gradle): Gradle构建脚本替换为Kotlin DSL

---

.github/workflows/gradle-build.yml
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy

fix(gradle): 标准化catalog配置

---

gradle/wrapper/gradle-wrapper.properties
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-java/src/test/groovy/pub/ihub/plugin/java/IHubJavaPluginTest.groovy

build(gradle): 升级gradle至8.2.1

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/copyright/IHubCopyrightPlugin.groovy

fix(copyright): 修正copyright生成的配置文件编辑嵌套空行

---

.github/workflows/gradle-build.yml
.github/workflows/gradle-dependency-submission.yml
.github/workflows/gradle-publish.yml
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
ihub-base/build.gradle.kts
ihub-base/src/main/groovy/pub/ihub/plugin/IHubLibsVersions.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubLibsVersionsTest.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomExtension.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy
ihub-settings/build.gradle.kts
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
settings.gradle.kts

gradle(java): Java版本降至11

---

build.gradle.kts
gradle.properties
ihub-base/src/main/groovy/pub/ihub/plugin/IHubLibsVersions.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubLibsVersionsTest.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomExtension.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsExtension.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy
settings.gradle.kts

feat(gradle): 支持发布不同Java版本的platforms和catalog组件

---

build.gradle.kts
gradle/libs.versions.toml
ihub-base-test/src/main/groovy/pub/ihub/plugin/test/IHubSpecification.groovy
ihub-base-test/src/main/resources/libs.versions.toml
ihub-base/build.gradle.kts
ihub-base/src/main/groovy/pub/ihub/plugin/IHubProjectPluginAware.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubSimplePlugin.groovy
ihub-groovy/src/main/groovy/pub/ihub/plugin/groovy/IHubGroovyPlugin.groovy
ihub-java/build.gradle.kts
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy

feat(java8): 插件兼容Java1.8

---

build.gradle.kts
ihub-base/build.gradle.kts
ihub-base/src/test/groovy/pub/ihub/plugin/IHubLibsVersionsTest.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaExtension.groovy
ihub-java/src/test/groovy/pub/ihub/plugin/java/IHubJavaPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy

test(java8): 修正测试用例

---

README.md
build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

build(gradle): 依赖组件整理

---

ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

feat(settings): ihub-settings支持iHub.profile配置替换libs.versions.toml版本配置

---

README.md
ihub-plugins/build.gradle.kts
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/profiles/IHubProfilesExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/profiles/IHubProfilesPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/profiles/IHubProfilesPluginTest.groovy
ihub-spring/src/main/groovy/pub/ihub/plugin/spring/IHubBootPlugin.groovy
ihub-spring/src/test/groovy/pub/ihub/plugin/spring/IHubBootPluginTest.groovy

feat(profiles): 新增ihub-profiles插件

---

ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

fix(dependencies): 修复ihub-test组件默认依赖配置

---

README.md
gradle/libs.versions.toml
ihub-base/src/main/groovy/pub/ihub/plugin/IHubPlugin.groovy
ihub-base/src/main/groovy/pub/ihub/plugin/IHubProjectPluginAware.groovy
ihub-base/src/main/groovy/pub/ihub/plugin/IHubTask.groovy
ihub-node/build.gradle.kts
ihub-node/src/main/groovy/pub/ihub/plugin/node/IHubNodeExtension.groovy
ihub-node/src/main/groovy/pub/ihub/plugin/node/IHubNodePlugin.groovy
ihub-node/src/main/groovy/pub/ihub/plugin/node/cnpm/exec/CnpmExecRunner.groovy
ihub-node/src/main/groovy/pub/ihub/plugin/node/cnpm/task/CnpmInstallTask.groovy
ihub-node/src/main/groovy/pub/ihub/plugin/node/cnpm/task/CnpmSetupTask.groovy
ihub-node/src/main/groovy/pub/ihub/plugin/node/cnpm/task/CnpmSyncTask.groovy
ihub-node/src/main/groovy/pub/ihub/plugin/node/cnpm/task/CnpmTask.groovy
ihub-node/src/test/groovy/pub/ihub/plugin/node/IHubNodePluginTest.groovy

feat(node): 新增ihub-node插件

---

ihub-base/src/main/groovy/pub/ihub/plugin/IHubPluginMethods.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubPluginBaseTest.groovy
settings.gradle.kts

chore: 优化控制台打印表格

---

ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

fix(verification): 修正verification组件pmd依赖

---

ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

feat(settings): 没有配置指定子项目时，自动添加所有子项目

---

ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

fix(verification): 修正PMD依赖

---

build.gradle.kts
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

chore(bom): 项目不包含dependencies组件时，自动配置ihub-bom

---

gradle/wrapper/gradle-wrapper.properties
gradlew

build(gradle): 升级gradle至8.4

---

README.md
gradle/libs.versions.toml
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-java/src/test/groovy/pub/ihub/plugin/java/IHubJavaPluginTest.groovy
ihub-shadow/build.gradle.kts
ihub-shadow/src/main/groovy/pub/ihub/plugin/shadow/IHubShadowExtension.groovy
ihub-shadow/src/main/groovy/pub/ihub/plugin/shadow/IHubShadowPlugin.groovy
ihub-shadow/src/test/groovy/pub/ihub/plugin/shadow/IHubShadowPluginTest.groovy

feat(shadow): 新增ihub-shadow插件，集成Shadow支持构建uberjar

---

README.md
gradle/libs.versions.toml
ihub-base/src/main/groovy/pub/ihub/plugin/IHubDependencyAware.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubDemoExtension.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubDependencyPlugin.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubPluginBaseTest.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomExtension.groovy
ihub-groovy/src/main/groovy/pub/ihub/plugin/groovy/IHubGroovyPlugin.groovy
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-javaagent/build.gradle.kts
ihub-javaagent/src/main/groovy/pub/ihub/plugin/javaagent/IHubJavaagentExtension.groovy
ihub-javaagent/src/main/groovy/pub/ihub/plugin/javaagent/IHubJavaagentPlugin.groovy
ihub-javaagent/src/test/groovy/pub/ihub/plugin/javaagent/IHubJavaagentPluginTest.groovy
ihub-javaagent/src/test/resources/META-INF/gradle-plugins/org.springframework.boot.properties
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy
ihub-verification/src/test/groovy/pub/ihub/plugin/verification/IHubVerificationPluginTest.groovy

feat(javaagent): 新增ihub-javaagent插件，支持启动配置代理插件

---

gradle/libs.versions.toml

ci: byte-buddy版本升级

---

ihub-base/src/main/groovy/pub/ihub/plugin/IHubDependencyAware.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomExtension.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/impl/Module.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/impl/ModuleSpecImpl.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/impl/Modules.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/impl/ModulesSpecImpl.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
settings.gradle.kts

fix(bom): 修正bom版本组件组件配置

---

gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

build(gradle): 升级gradle至8.6

---

ihub-base/src/main/groovy/pub/ihub/plugin/IHubProjectPluginAware.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubPluginBaseTest.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubPrintPlugin.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy

chore(clean): 根项目添加默认clean任务

---

ihub-shadow/src/main/groovy/pub/ihub/plugin/shadow/IHubShadowPlugin.groovy

fix(shadow): 修复ihub-shadow组件发布签名错误

---

gradle.properties
ihub-javaagent/src/main/groovy/pub/ihub/plugin/javaagent/IHubJavaagentExtension.groovy
ihub-javaagent/src/main/groovy/pub/ihub/plugin/javaagent/IHubJavaagentPlugin.groovy
ihub-shadow/src/main/groovy/pub/ihub/plugin/shadow/IHubShadowPlugin.groovy
ihub-shadow/src/test/groovy/pub/ihub/plugin/shadow/IHubShadowPluginTest.groovy

feat(javaagent): ihub-javaagent扩展参数支持classifier

---

gradle/libs.versions.toml
ihub-publish/build.gradle.kts
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishExtension.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy

feat(maven-central): 升级ihub-publish组件，支持发布maven-central仓库

---

ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy

test(maven-central): 升级ihub-publish组件，支持发布maven-central仓库

---

ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
samples/sample-extensions/bom.gradle

fix(groovy): groovy插件不能与Lombok同时使用

---

ihub-base/src/main/groovy/pub/ihub/plugin/IHubLibsVersions.groovy
ihub-base/src/test/groovy/pub/ihub/plugin/IHubLibsVersionsTest.groovy
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/IHubBomPlugin.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-javaagent/src/main/groovy/pub/ihub/plugin/javaagent/IHubJavaagentPlugin.groovy
ihub-javaagent/src/test/groovy/pub/ihub/plugin/javaagent/IHubJavaagentPluginTest.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsExtension.groovy
ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy
ihub-plugins/src/test/groovy/pub/ihub/plugin/IHubPluginsPluginTest.groovy
ihub-settings/src/main/groovy/pub/ihub/plugin/IHubSettingsPlugin.groovy

chore: 增加本地调试参数

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy

- 将 Gradle 版本从 8.12.1 升级到 8.13
- 注释掉 build.gradle.kts 中的验证相关插件和配置- 修改 IHubTestPlugin 中的测试报告类型

build: 更新 Gradle 版本并调整构建配置

---

ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubTestPlugin.groovy
ihub-verification/src/main/groovy/pub/ihub/plugin/verification/IHubVerificationPlugin.groovy

- 将双引号字符串改为单引号字符串，以统一代码风格
- 修改涉及 IHubTestPlugin 和 IHubVerificationPlugin 文件

style(ihub-verification): 代码格式化调整

---

build.gradle.kts
ihub-bom/src/main/groovy/pub/ihub/plugin/bom/specs/DependencySpec.groovy
ihub-bom/src/test/groovy/pub/ihub/plugin/bom/IHubBomPluginTest.groovy
ihub-groovy/src/main/groovy/pub/ihub/plugin/groovy/IHubGroovyPlugin.groovy
ihub-java/build.gradle.kts
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaBasePlugin.groovy
ihub-java/src/main/groovy/pub/ihub/plugin/java/IHubJavaPlugin.groovy
ihub-kotlin/src/main/groovy/pub/ihub/plugin/kotlin/IHubKotlinPlugin.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishExtension.groovy
ihub-publish/src/main/groovy/pub/ihub/plugin/publish/IHubPublishPlugin.groovy
ihub-publish/src/test/groovy/pub/ihub/plugin/publish/IHubPublishPluginTest.groovy
ihub-settings/src/test/groovy/pub/ihub/plugin/IHubSettingsPluginTest.groovy

- 新增 IHubJavaBasePlugin 作为 Java 插件的基础
- 修改 IHubJavaPlugin 和 IHubKotlinPlugin 依赖新的基础插件- 更新 IHubBomPlugin 和 IHubPublishPlugin 以适应新的插件结构
- 修复 Groovy 插件与 Java 注解处理器的冲突
- 优化配置文件读取逻辑

refactor(java): 重构 Java 插件体系

---

ihub-plugins/src/main/groovy/pub/ihub/plugin/IHubPluginsPlugin.groovy

- 在 IHubPluginsPlugin 中同时应用 IHubVersionPlugin 和 IHubBomPlugin -移除单独应用 IHubVersionPlugin 的代码行
- 更新注释以反映新的插件应用逻辑

build(ihub): 默认应用 IHubVersion、IHubBom 插件
